name: GetARock Swift-Builder

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, release, hotfix, feature ]

jobs:
  build:
    name: Build and Test by Swift
    runs-on: macos-latest

    steps:
      - name: 🟢 Checkout Source Code 🟢
        uses: actions/checkout@v3
        
      - name: 🔵 Build Test Step 🔵
        run: |
          xcodebuild test -project ./GithubActionTest/GithubActionTest.xcodeproj -scheme GithubActionTest -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"
